name: Update Script and Display Current Time

on:
  push:
    paths:
      - 'scripts/my-script.sh'  # 监控特定的脚本文件

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get current time
      id: get_time
      run: echo "::set-output name=current_time::$(date +'%Y-%m-%d %H:%M:%S')"

    - name: Display current time
      run: echo "Current time is ${{ steps.get_time.outputs.current_time }}"

    - name: Give execute permission to the script
      run: chmod +x scripts/my-script.sh

    - name: Run the updated script
      run: ./scripts/my-script.sh

    - name: Display a final message with the time
      run: echo "Script executed at ${{ steps.get_time.outputs.current_time }}"
